// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Pedidos;

{ITE} {DFMFileType} {View\UPrincipal.dfm}
{ITE} {RCFileType} {Win32\Debug\Pedidos_DRC.rc}

{$R 'View\UPrincipal.dfm' 'Form1:TForm'}
{$R 'Win32\Debug\Pedidos_DRC.res' 'Win32\Debug\Pedidos_DRC.rc'}

{$E PTB}

begin
end.
